# Form implementation generated from reading ui file 'InputWindow_Interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 259)
        Form.setMaximumSize(QtCore.QSize(500, 16777215))
        Form.setAcceptDrops(False)
        Form.setStyleSheet("#Form {\n"
"    background-color: #474E68;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #50577A;\n"
"    border-radius: 3px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #EC47ED;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #50577A;\n"
"    border-radius: 3px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6B728E\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_frametitle = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_frametitle.setFont(font)
        self.label_frametitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_frametitle.setObjectName("label_frametitle")
        self.horizontalLayout.addWidget(self.label_frametitle)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 15)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_name = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(50, 0))
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_2.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_name.setSizePolicy(sizePolicy)
        self.lineEdit_name.setMaximumSize(QtCore.QSize(16755, 30))
        self.lineEdit_name.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEdit_name.setStyleSheet("")
        self.lineEdit_name.setInputMask("")
        self.lineEdit_name.setText("")
        self.lineEdit_name.setFrame(False)
        self.lineEdit_name.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_quantity = QtWidgets.QLabel(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_quantity.sizePolicy().hasHeightForWidth())
        self.label_quantity.setSizePolicy(sizePolicy)
        self.label_quantity.setMinimumSize(QtCore.QSize(50, 0))
        self.label_quantity.setObjectName("label_quantity")
        self.horizontalLayout_3.addWidget(self.label_quantity)
        self.lineEdit_quantity = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_quantity.setFrame(False)
        self.lineEdit_quantity.setObjectName("lineEdit_quantity")
        self.horizontalLayout_3.addWidget(self.lineEdit_quantity)
        self.label_totlacprice = QtWidgets.QLabel(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totlacprice.sizePolicy().hasHeightForWidth())
        self.label_totlacprice.setSizePolicy(sizePolicy)
        self.label_totlacprice.setMinimumSize(QtCore.QSize(50, 0))
        self.label_totlacprice.setObjectName("label_totlacprice")
        self.horizontalLayout_3.addWidget(self.label_totlacprice)
        self.lineEdit_totalprice = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit_totalprice.setFrame(False)
        self.lineEdit_totalprice.setObjectName("lineEdit_totalprice")
        self.horizontalLayout_3.addWidget(self.lineEdit_totalprice)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_date = QtWidgets.QLabel(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setMinimumSize(QtCore.QSize(55, 0))
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 0, 0, 1, 1)
        self.label_storage = QtWidgets.QLabel(parent=self.frame_6)
        self.label_storage.setObjectName("label_storage")
        self.gridLayout.addWidget(self.label_storage, 1, 0, 1, 1)
        self.lineEdit_storage = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit_storage.setObjectName("lineEdit_storage")
        self.gridLayout.addWidget(self.lineEdit_storage, 1, 1, 1, 1)
        self.lineEdit_date = QtWidgets.QLineEdit(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_date.sizePolicy().hasHeightForWidth())
        self.lineEdit_date.setSizePolicy(sizePolicy)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.gridLayout.addWidget(self.lineEdit_date, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(parent=Form)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_cancel.setFlat(False)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_6.addWidget(self.pushButton_cancel)
        self.pushButton_subbmit = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_subbmit.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_subbmit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_subbmit.setObjectName("pushButton_subbmit")
        self.horizontalLayout_6.addWidget(self.pushButton_subbmit)
        self.verticalLayout.addWidget(self.frame_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New asset"))
        self.label_frametitle.setText(_translate("Form", "New asset"))
        self.label_name.setText(_translate("Form", "Name"))
        self.label_quantity.setText(_translate("Form", "Quantity"))
        self.label_totlacprice.setText(_translate("Form", "  Total price"))
        self.label_date.setText(_translate("Form", "Date"))
        self.label_storage.setText(_translate("Form", "Storage place"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_subbmit.setText(_translate("Form", "Confirm"))
